### ISSUE TITLE
CentOS boxes fails with authentication errors

### ISSUE THREAD

**Issue by ggeldenhuis** [puppetlabs/puppet-vagrant-boxes#44]
Currently any vagrant box centos related found on https://atlas.hashicorp.com/puppetlabs his coming up with an authentication error:

```
    mdm01.example.com: SSH username: vagrant
    mdm01.example.com: SSH auth method: private key
    mdm01.example.com: Warning: Connection refused. Retrying...
    mdm01.example.com:
    mdm01.example.com: Vagrant insecure key detected. Vagrant will automatically replace
    mdm01.example.com: this with a newly generated keypair for better security.
    mdm01.example.com:
    mdm01.example.com: Inserting generated public key within guest...
    mdm01.example.com: Removing insecure key from the guest if it's present...
    mdm01.example.com: Key inserted! Disconnecting and reconnecting using new SSH key...
    mdm01.example.com: Warning: Authentication failure. Retrying...
    mdm01.example.com: Warning: Authentication failure. Retrying...
```

This is confirmed for:
- puppetlabs/centos-6.5-64-nocm              (vmware_desktop, 1.0.0)
- puppetlabs/centos-6.6-64-puppet            (vmware_desktop, 1.0.3)
- puppetlabs/centos-6.6-64-puppet-enterprise (vmware_desktop, 1.0.3)
- puppetlabs/centos-7.2-64-nocm              (vmware_desktop, 1.0.0)
- puppetlabs/centos-7.2-64-nocm              (vmware_desktop, 1.0.1)
- puppetlabs/centos-7.2-64-puppet            (vmware_desktop, 1.0.1)

Ubuntu boxes works just fine. 
Perhaps it is time for a box refresh?
